# Generated by Django 4.2.1 on 2023-06-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_meal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_calories', models.IntegerField()),
                ('total_fat', models.IntegerField()),
                ('total_protein', models.IntegerField()),
                ('total_carbs', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='foods',
            field=models.ManyToManyField(to='main_app.food'),
        ),
    ]
