# Generated by Django 4.2.1 on 2023-06-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_foods_meal_foods'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foods',
            new_name='Food',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='foods',
        ),
    ]
