# Generated by Django 4.2.1 on 2023-06-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_food_meal_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='total_carbs',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_fat',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_protein',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
