# Generated by Django 4.2.1 on 2023-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_food_total_carbs_alter_food_total_fat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='total_carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_protein',
            field=models.IntegerField(),
        ),
    ]
