# Generated by Django 4.2.1 on 2023-06-08 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_food_total_carbs_alter_food_total_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
