# Generated by Django 4.2.1 on 2023-06-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_foods_food_remove_meal_foods'),
        ('main_app', '0006_alter_food_total_carbs_alter_food_total_fat_and_more'),
    ]

    operations = [
    ]
