# Generated by Django 4.2.1 on 2023-06-08 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_food_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='date_added',
        ),
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='meal date'),
            preserve_default=False,
        ),
    ]
